# TDC Porto Alegre

In [ ]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

![cover](./images/cover.png)

![cover](./images/o-que-e-ciencia-de-dados.png)

![multidisciplinaridade](./images/multidisciplinaridade.png)

![na-vida-real](./images/na-vida-real.png)

![linkedin](./images/linkedin.png)

![cancer](./images/cancer.png)

![imoveis-california](./images/imoveis-california.png)

![reconhecimento-fala](./images/reconhecimento-fala.png)

![kinnect](./images/kinnect.png)

![netflix](./images/netflix.png)

![machine-learning](./images/machine-learning.png)

![modelos-preditivos](./images/modelos-preditivos.png)

![scikit-learn](./images/scikit-learn.png)

![oreilly](./images/oreilly.png)

# 1. Comprometimento com usabilidade e documentação


# 2. Equipe de especialistas dedicada para implementar algoritmos

# 3. Cobertura da maior parte dos passos necessárias


# 4. Facilidade em interagir com conjunto de dados

# 5. Biblioteca é focada em Machine Learning

# 6. É escalável para resolver a maior parte dos problemas existentes

![install](./images/install.png)

![install-recommendation](./images/install-recommendation.png)

![step1](./images/step1.png)

![iris-dataset](./images/iris-dataset.png)

![sepala](./images/sepala.png)

# Você pode encontrar este conjunto no UCI

In [1]:
from IPython.display import IFrame
IFrame('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', width=700, height=1000)

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
type(iris)
# Conjunto de dados carregados consiste em um objeto diferente: 'bunch'

sklearn.datasets.base.Bunch

In [4]:
# Propriedade feature_names acessa... atributos (features)
print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
# Propriedade data acessa... matriz de amostras (sample, example, instance, record)
print (iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [6]:
# Propriedade target_names acessa... nome das classes
print (iris.target_names)

['setosa' 'versicolor' 'virginica']


In [7]:
# Propriedade target acessa... vetor de alvos/respostas
print (iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


![irises](./images/irises.png)

![step2](./images/step2.png)

# Antes de treinar o modelo, certifique-se que...

* Amostras e Alvos estão armazenados em **objetos diferentes**

* Amostras e Alvos estão representados por **valores numéricos**

* Amostras e Alvos estão armazenados em **arrays NumPy**

* Amostras e Alvos possuem **tamanhos (*shapes*) específicos**

In [8]:
print (type(iris.data))
print (type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
print (iris.data.shape)

(150, 4)


In [10]:
print(iris.target.shape)

(150,)


In [11]:
# Armazene atributos e alvos em objetos diferentes
X = iris.data
Y = iris.target

Mais informações sobre conjuntos de dados em http://scikit-learn.org/stable/datasets/

![step3](./images/step3.png)

# Como treinar modelos?

In [12]:
# importa algoritmo para treinar modelo com Regressão Logística
from sklearn.linear_model import LogisticRegression

In [13]:
# Instanciar o modelo (utilizando parâmetros padrões)
logistic_regression = LogisticRegression()

In [14]:
# construir o modelo a partir das amostras e do alvo. É nesse momento que o modelo aprende com os dados.
logistic_regression.fit(X, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
# Predição para novas observações
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
logistic_regression.predict(X_new)

array([2, 0])

In [16]:
print (iris.target_names)

['setosa' 'versicolor' 'virginica']


Mais informações em http://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

# Como treinar modelos?

In [17]:
# Importa algoritmo para treinar modelo com árvore de decisão
from sklearn.tree import DecisionTreeClassifier

In [18]:
# Instanciar o modelo (utilizando parâmetros padrões)
decision_tree = DecisionTreeClassifier()

In [19]:
# construir o modelo a partir das amostras e do alvo. É nesse momento que o modelo aprende com os dados.
decision_tree.fit(X, Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [20]:
# Predição para novas observações
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
decision_tree.predict(X_new)

array([1, 1])

In [21]:
print (iris.target_names)

['setosa' 'versicolor' 'virginica']


Mais informações em http://scikit-learn.org/stable/modules/tree#classification